export const PROFILE_REQUEST = "PROFILE_REQUEST";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const PROFILE_FAIL = "PROFILE_FAIL";

export const EDIT_PROFILE_REQUEST = "EDIT_PROFILE_REQUEST";
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";
export const EDIT_PROFILE_FAIL = "EDIT_PROFILE_FAIL";

export const PUBLIC_PROFILE_REQUEST = "PUBLIC_PROFILE_REQUEST";
export const PUBLIC_PROFILE_SUCCESS = "PUBLIC_PROFILE_SUCCESS";
export const PUBLIC_PROFILE_FAIL = "PUBLIC_PROFILE_FAIL";

export const PROFILE_LIST_REQUEST = "PROFILE_LIST_REQUEST";
export const PROFILE_LIST_SUCCESS = "PROFILE_LIST_SUCCESS";
export const PROFILE_LIST_FAIL = "PROFILE_LIST_FAIL";

export const UPDATE_SEARCH_FOR_PROFILE_LIST =
  "UPDATE_SEARCH_FOR_PUBLIC_PROFILE_LIST";

const NO_MIN_LENGTH = 0;

const FIRSTNAME_MIN_LENGTH = 1;
const FIRSTNAME_MAX_LENGTH = 50;

const LASTNAME_MIN_LENGTH = 1;
const LASTNAME_MAX_LENGTH = 50;

const SHORTINTRO_MAX_LENGTH = 200;
const ABOUT_MAX_LENGTH = 3000;
const CITY_MAX_LENGTH = 50;
const COUTRY_MAX_LENGTH = 50;
const SOCIAL_MAX_LENGTH = 200;

export const PROFILE_VALIDATION = {
  NO_MIN_LENGTH,
  FIRSTNAME_MIN_LENGTH,
  FIRSTNAME_MAX_LENGTH,
  LASTNAME_MIN_LENGTH,
  LASTNAME_MAX_LENGTH,
  SHORTINTRO_MAX_LENGTH,
  ABOUT_MAX_LENGTH,
  CITY_MAX_LENGTH,
  COUTRY_MAX_LENGTH,
  SOCIAL_MAX_LENGTH,
};
