export const DEVELOPER_REQUEST = "DEVELOPER_REQUEST";
export const DEVELOPER_SUCCESS = "DEVELOPER_SUCCESS";
export const DEVELOPER_FAIL = "DEVELOPER_FAIL";

export const EDIT_DEVELOPER_REQUEST = "EDIT_DEVELOPER_REQUEST";
export const EDIT_DEVELOPER_SUCCESS = "EDIT_DEVELOPER_SUCCESS";
export const EDIT_DEVELOPER_FAIL = "EDIT_DEVELOPER_FAIL";

export const PUBLIC_DEVELOPER_REQUEST = "PUBLIC_DEVELOPER_REQUEST";
export const PUBLIC_DEVELOPER_SUCCESS = "PUBLIC_DEVELOPER_SUCCESS";
export const PUBLIC_DEVELOPER_FAIL = "PUBLIC_DEVELOPER_FAIL";

export const DEVELOPER_LIST_REQUEST = "DEVELOPER_LIST_REQUEST";
export const DEVELOPER_LIST_SUCCESS = "DEVELOPER_LIST_SUCCESS";
export const DEVELOPER_LIST_FAIL = "DEVELOPER_LIST_FAIL";

export const UPDATE_SEARCH_FOR_DEVELOPER_LIST =
  "UPDATE_SEARCH_FOR_PUBLIC_DEVELOPER_LIST";

const NO_MIN_LENGTH = 0;

const FIRSTNAME_MIN_LENGTH = 1;
const FIRSTNAME_MAX_LENGTH = 50;

const LASTNAME_MIN_LENGTH = 1;
const LASTNAME_MAX_LENGTH = 50;

const SHORTINTRO_MAX_LENGTH = 200;
const ABOUT_MAX_LENGTH = 3000;
const CITY_MAX_LENGTH = 50;
const COUTRY_MAX_LENGTH = 50;
const SOCIAL_MAX_LENGTH = 200;

export const DEVELOPER_VALIDATION = {
  NO_MIN_LENGTH,
  FIRSTNAME_MIN_LENGTH,
  FIRSTNAME_MAX_LENGTH,
  LASTNAME_MIN_LENGTH,
  LASTNAME_MAX_LENGTH,
  SHORTINTRO_MAX_LENGTH,
  ABOUT_MAX_LENGTH,
  CITY_MAX_LENGTH,
  COUTRY_MAX_LENGTH,
  SOCIAL_MAX_LENGTH,
};
