export const PRIVATE_PROFILE_REQUEST = "PRIVATE_PROFILE_REQUEST";
export const PRIVATE_PROFILE_SUCCESS = "PRIVATE_PROFILE_SUCCESS";
export const PRIVATE_PROFILE_FAIL = "PRIVATE_PROFILE_FAIL";

export const EDIT_PRIVATE_PROFILE_REQUEST = "EDIT_PRIVATE_PROFILE_REQUEST";
export const EDIT_PRIVATE_PROFILE_SUCCESS = "EDIT_PRIVATE_PROFILE_SUCCESS";
export const EDIT_PRIVATE_PROFILE_FAIL = "EDIT_PRIVATE_PROFILE_FAIL";
