export const PRIVATE_PROFILE_REQUEST = "PRIVATE_PROFILE_REQUEST";
export const PRIVATE_PROFILE_SUCCESS = "PRIVATE_PROFILE_SUCCESS";
export const PRIVATE_PROFILE_FAIL = "PRIVATE_PROFILE_FAIL";

export const EDIT_PRIVATE_PROFILE_REQUEST = "EDIT_PRIVATE_PROFILE_REQUEST";
export const EDIT_PRIVATE_PROFILE_SUCCESS = "EDIT_PRIVATE_PROFILE_SUCCESS";
export const EDIT_PRIVATE_PROFILE_FAIL = "EDIT_PRIVATE_PROFILE_FAIL";

const NO_MIN_LENGTH = 0;

const FIRSTNAME_MIN_LENGTH = 1;
const FIRSTNAME_MAX_LENGTH = 50;

const LASTNAME_MIN_LENGTH = 1;
const LASTNAME_MAX_LENGTH = 50;

const SHORTINTRO_MAX_LENGTH = 200;
const ABOUT_MAX_LENGTH = 3000;
const CITY_MAX_LENGTH = 50;
const COUTRY_MAX_LENGTH = 50;
const SOCIAL_MAX_LENGTH = 200;

export const PROFILE_VALIDATION = {
  NO_MIN_LENGTH,
  FIRSTNAME_MIN_LENGTH,
  FIRSTNAME_MAX_LENGTH,
  LASTNAME_MIN_LENGTH,
  LASTNAME_MAX_LENGTH,
  SHORTINTRO_MAX_LENGTH,
  ABOUT_MAX_LENGTH,
  CITY_MAX_LENGTH,
  COUTRY_MAX_LENGTH,
  SOCIAL_MAX_LENGTH,
};
