const NO_MIN_LENGTH = 0;

const PROJECTNAME_MIN_LENGTH = 5;
const PROJECTNAME_MAX_LENGTH = 100;

export const PROJECT_VALIDATION = {
  NO_MIN_LENGTH,
  PROJECTNAME_MIN_LENGTH,
  PROJECTNAME_MAX_LENGTH,
};
