const NO_MIN_LENGTH = 0;

const PROJECTNAME_MIN_LENGTH = 3;
const PROJECTNAME_MAX_LENGTH = 100;
const ABOUT_MAX_LENGTH = 3000;

export const PROJECT_VALIDATION = {
  NO_MIN_LENGTH,
  PROJECTNAME_MIN_LENGTH,
  PROJECTNAME_MAX_LENGTH,
  ABOUT_MAX_LENGTH,
};
